main: com.kamilereon.storyteller.main.StoryTellerMain
name: storyteller
version: 0.1
api-version: 1.17
author: kamilereon
description: simple framework / plugin for implementing com.kamilereon.storyteller.quest system
commands:
  story:
    description: command prefix for storyteller
    usage: /story